title: Victoria Junior College
url: https://victoriajc.moe.edu.sg
favicon: /images/VJCCrest.png
colors:
  primary-color: "#a41212"
  secondary-color: "#a41212"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#a41212"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Founded in 1984, Victoria Junior College aims to ignite the
  imagination of all Victorians to create the future with conviction, courage
  and compassion.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d31hymonz16767.amplifyapp.com
prod: https://master.d31hymonz16767.amplifyapp.com
resources_name: happenings-at-vjc
shareicon: /images/VJCCrest.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
